### ISSUE TITLE
Code Companion seems to have an incomplete prompt

### ISSUE THREAD

**Issue by nviraj** [friuns2/Leaked-GPTs#1]
Was just checking random prompts from the repo, seems cool!

[Code Companion](https://github.com/friuns2/Leaked-GPTs/blob/main/gpts/%F0%9F%A4%93CodeCompanion.md) seems to have an incomplete prompt.

Last line of the prompt is:

> Use your knowledge: I have multiple resources at my disposable, the

**Comment by friuns2** [comment]
fixed thanks for report

**Comment by Wladefant** [comment]
can be closed?
